[package]
name="demo"
version="0.1.0"
authors = ["Serenity <removed>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phrases = { path = "../phrases"}